//! The corpus's own README, generated from the builders.
//!
//! # Why documentation of a generated tree is generated too
//!
//! `fixtures/` is a directory a reader opens without running anything, and a hand-written
//! index of it is a file that goes stale the first time a fixture is added. Generating it
//! makes the index a *checked* statement: the `verification` suite asserts the committed
//! README is what the builders describe, so adding a fixture without regenerating fails
//! a test rather than leaving a file nobody notices is out of date.

use std::fmt::Write as _;

use crate::captures;
use crate::documents::{self, GraphKind, ImpactKind, ProvenanceKind, ReportKind, SetKind};
use crate::recordings;
use crate::wasm_modules;

/// The corpus README's text.
///
/// # Panics
///
/// Panics when a builder refuses a document, which would mean the corpus itself could
/// not be built - a condition the suites fail on anyway, reported here rather than
/// silently documented.
#[must_use]
pub fn render() -> String {
    let mut text = String::new();
    text.push_str(
        "<!-- Generated by `generate-fixtures`. Edit the builders, not this file. -->\n\n\
         # The fixture corpus\n\n\
         Almost every file here is written by\n\
         `cargo run -p amasario-integration-tests --bin generate-fixtures`, which builds\n\
         each document from the engine's own types. Each suite under `integration-tests/`\n\
         asserts that the committed bytes equal what the builders produce - so a diff in\n\
         this directory means the model changed.\n\n\
         The exception is the four files marked *captured* below. Those are transcriptions\n\
         of responses a live testnet endpoint returned, committed verbatim, together with\n\
         the request that produced them and the day it was read. They are not generated,\n\
         because a generated response would encode the assumption under test: three of the\n\
         defects this engine has had - the reading of a nested call, the location of the\n\
         host's diagnostic events, and the event index's own floor - were invisible in\n\
         every hand-written document and obvious in these.\n\n\
         A fixture is not a claim about a network. The *recorded* files under\n\
         `transactions/`, `ledgers/` and `contracts/` are shaped like the documented\n\
         Stellar RPC and Horizon responses they stand in for, so that the adapters' own\n\
         parsers are what decode them; they were not read off a chain. The *captured*\n\
         files were, and they are labelled as such. No analysis result is asserted that\n\
         was not derived from a document in this directory.\n\n\
         ## Contents\n\n",
    );

    let sections: Vec<(&str, &str, Vec<(String, String)>)> = vec![
        (
            "contracts/",
            "Contract identities built with `ContractIdentity::new`, one per executable kind \
             and one observing an upgrade; plus recorded JSON-RPC error bodies.",
            {
                let mut files: Vec<(String, String)> = documents::contract_identities()
                    .into_iter()
                    .map(|(name, identity)| {
                        (
                            format!("{name}.json"),
                            format!(
                                "{} at ledger {}",
                                identity.executable_kind.as_str(),
                                identity.resolved_at_ledger.get()
                            ),
                        )
                    })
                    .collect();
                files.extend(
                    recordings::all()
                        .into_iter()
                        .filter(|recording| recording.directory == "contracts")
                        .map(|recording| (recording.file.to_owned(), recording.note.to_owned())),
                );
                files
            },
        ),
        (
            "dependencies/",
            "Dependency-set documents in the specification's shape, produced by resolving \
             recorded invocations. A refusal is published as an `unresolved` entry with reason \
             `NOT_PERMITTED` and the engine's explanation in `detail`, so that an absent edge \
             is never mistaken for an absent dependency.",
            SetKind::all()
                .iter()
                .map(|kind| (format!("{}.json", kind.file()), describe_set(*kind)))
                .collect(),
        ),
        (
            "graphs/",
            "Graph documents produced by assembling a set's edges and bounding traversal.",
            GraphKind::all()
                .iter()
                .map(|kind| (format!("{}.json", kind.file()), describe_graph(*kind)))
                .collect(),
        ),
        (
            "impact/",
            "Finding sets produced by propagating a declared change through the graph.",
            ImpactKind::all()
                .iter()
                .map(|kind| (format!("{}.json", kind.file()), describe_impact(*kind)))
                .collect(),
        ),
        (
            "ledgers/",
            "Recorded ledger and network-identity responses, alongside the captured \
             responses that fix the retention window's floor and the event page's shape.",
            {
                let mut files: Vec<(String, String)> = recordings::all()
                    .into_iter()
                    .filter(|recording| recording.directory == "ledgers")
                    .map(|recording| (recording.file.to_owned(), recording.note.to_owned()))
                    .collect();
                files.extend(captures_of("ledgers"));
                files
            },
        ),
        (
            "provenance/",
            "Provenance chains, including one whose deployment disagrees with its build and \
             is therefore marked `CONFLICTING` rather than `VERIFIED`.",
            ProvenanceKind::all()
                .iter()
                .map(|kind| (format!("{}.json", kind.file()), describe_provenance(*kind)))
                .collect(),
        ),
        (
            "snapshots/",
            "Two captures of one contract at one boundary, differing so that a diff has an \
             added edge, a changed module digest and a changed confidence to report. The \
             names are what the `Integration` workflow globs for when it exercises \
             `amasario diff`.",
            vec![
                (
                    "testnet-alpha-before.json".to_owned(),
                    "the earlier capture".to_owned(),
                ),
                (
                    "testnet-alpha-after.json".to_owned(),
                    "the later capture".to_owned(),
                ),
            ],
        ),
        (
            "transactions/",
            "Recorded transaction responses, including one the ledger reports as failed, \
             alongside two captured transactions: one that made a nested call and one that \
             did not.",
            {
                let mut files: Vec<(String, String)> = recordings::all()
                    .into_iter()
                    .filter(|recording| recording.directory == "transactions")
                    .map(|recording| (recording.file.to_owned(), recording.note.to_owned()))
                    .collect();
                files.extend(captures_of("transactions"));
                files
            },
        ),
        (
            "wasm/",
            "Real WebAssembly modules stored as hex, with the digest computed over their \
             bytes. None has a contract spec section, and two are not modules at all, so that \
             the refusal to invent an interface can be asserted rather than assumed.",
            wasm_modules::all()
                .iter()
                .map(|spec| {
                    let length = (spec.bytes)().len();
                    (
                        format!("{}.json", spec.name),
                        format!("{length} byte(s); {}", spec.note),
                    )
                })
                .collect(),
        ),
        (
            "expected-reports/",
            "Report documents in the specification's shape, each checked with its own \
             `failures()` before it is written.",
            ReportKind::all()
                .iter()
                .map(|kind| (format!("{}.json", kind.file()), describe_report(*kind)))
                .collect(),
        ),
    ];

    for (directory, description, files) in sections {
        let _ = write!(text, "### `{directory}`\n\n{description}\n\n");
        for (file, note) in files {
            let _ = writeln!(text, "* `{file}` - {note}");
        }
        text.push('\n');
    }

    text
}

/// The captures committed under one directory, as `(file, note)` pairs.
///
/// The note names the network, the day and the request, because a reader opening a
/// capture is looking at an opaque base64 blob and needs to know where it came from
/// before deciding anything about it.
fn captures_of(directory: &str) -> Vec<(String, String)> {
    captures::all()
        .into_iter()
        .filter(|capture| capture.directory == directory)
        .map(|capture| {
            (
                capture.file.to_owned(),
                format!(
                    "*captured* from {} by `{}` on {}; {}",
                    capture.network, capture.method, capture.captured, capture.note
                ),
            )
        })
        .collect()
}

fn describe_set(kind: SetKind) -> String {
    match kind {
        SetKind::Direct => "two direct invocations".to_owned(),
        SetKind::Transitive => "a direct invocation closed into a two-hop chain".to_owned(),
        SetKind::Mixed => {
            "three direct edges - one from an operation, one from an event and one from a 
             call the ledger reported as failing - alongside one refused candidate"
                .to_owned()
        },
        SetKind::Refused => {
            "one call whose outcome the endpoint did not report, so no class could be \
             established and the refusal is published"
                .to_owned()
        },
    }
}

fn describe_graph(kind: GraphKind) -> String {
    match kind {
        GraphKind::Direct => "one subject, two outgoing edges".to_owned(),
        GraphKind::Transitive => "a two-hop chain".to_owned(),
        GraphKind::MultiHop => "a four-entity chain".to_owned(),
        GraphKind::Cyclic => {
            "a chain that closes back on itself, reported rather than collapsed".to_owned()
        },
        GraphKind::Disconnected => "a graph holding a contract no edge reaches".to_owned(),
    }
}

fn describe_impact(kind: ImpactKind) -> String {
    let analysis = documents::impact_analysis(kind);
    format!(
        "{} finding(s); {} changed; {} hop(s) of bound; deepest finding at {} hop(s); {}",
        analysis.findings.len(),
        analysis.changed.id,
        analysis.limits.max_depth,
        analysis.deepest(),
        if analysis.truncated {
            "truncated, and says so"
        } else {
            "reached everything within the bound"
        }
    )
}

fn describe_provenance(kind: ProvenanceKind) -> String {
    match kind {
        ProvenanceKind::Verified => "every link established, every link verified".to_owned(),
        ProvenanceKind::Partial => "source and build established, the deployment not".to_owned(),
        ProvenanceKind::UnknownSource => {
            "one link and no more, because the chain stops where the evidence does".to_owned()
        },
        ProvenanceKind::MismatchedWasm => {
            "a deployment whose module digest disagrees with the built one, marked CONFLICTING"
                .to_owned()
        },
    }
}

fn describe_report(kind: ReportKind) -> String {
    match kind {
        ReportKind::Verified => {
            "observed facts, an inferred relationship and a verification".to_owned()
        },
        ReportKind::UnknownProvenance => {
            "what was observed, and the question the engine cannot answer".to_owned()
        },
        ReportKind::CyclicDependencies => {
            "a graph with a cycle, and the question a cycle leaves open".to_owned()
        },
    }
}
